config/routes.rb
Rails.application.routes.draw do
 
  root :to  => 'session#index'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' =>'session#destroy' 

  get '/change_password' => 'users#change_password'
  patch '/change_password' => 'users#update_password'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trades, :types, :users, :journals
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  
  def new
  end

  def index
    render :layout => 'application'
  end

  def create
    create_session(params[:email], params[:password]);
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/index.html.erb
 <nav class="navbar fixed-top navbar-expand-lg navbar-dark  fs-4">
        <div class="container-fluid ">
          <a class="navbar-brand" href="/"><%= image_tag "logo_transparent.png"  %></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <span class="visually-hidden">(current)</span>
                </a>
              </li>
             <% if  @current_user.present? %>
               <li class="nav-item">
                  <%= link_to "Home", "/", class: "nav-link "%>
              </li>
              <li class="nav-item">
                  <%= link_to "Profile", trades_path, class: "nav-link " %>
              </li>
              
              <li class="nav-item">
                <%= link_to "Logout", login_path, method: 'delete' ,class: "nav-link " %>
              </li>
               <% else %>
                <li class="nav-item">
                <%= link_to "Login", login_path,class: "nav-link"  %>
              </li>
              <li class="nav-item">
                 <%= link_to "Signup", new_user_path, class: "nav-link " %>
              </li>
                <% end %>
            </ul>
          </div>
        </div>
</nav>
<div class="video-background">
  <div class="video-wrap">
    <div id="video">
     <%= video_tag "video.mp4", id: "idvideo",:autoplay => true, :loop => true, :muted => true, :playsinline => true %>
    </div>
  </div>
</div>
<div class="caption text-center text-light">
  <h1> TRADING JOURNAL </h1> 
  <h3> Keep track of your transactions</h3>
  <%= link_to "Get Started",new_user_path , class: "btn btn-outline-light " %>
</div>
</div>

app/views/session/new.html.erb
<div class="d-flex p-2 bd-highlight justify-content-center align-items-center" style="width:100% ; height: 100vh;">
<div class="card border-dark mb-3 col-md-2 card-width" >
   <div class="card-header">Welcome</div>
   <div class="card-body">
      <div class="text-center">
         <a class="navbar-brand" href="/" ><%= image_tag "logo_transparent.png"  %></a>
      </div>
      <%# we can use the form_with helper for generic forms that do not correspond to a model
         to do this we use a diferent syntax, we use 'url:some url here' instead of model @model %>
      <% if flash[:error] %>
      <strong> <%=  flash[:error] %></strong>
      <% end %>
      <%= form_with url: login_path, local: true do |f|  %>
      <div class="col-md-12">
         <%= f.label :email, class: 'form-label'  %>
         <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="col-md-12">
         <%= f.label :password, class: 'form-label'  %>
         <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="col-md-12 ">
         <%= f.submit 'Login',  class: 'btn btn-primary mt-3 col-md-4' %>
      </div>
      <% end %>
   </div>
</div>