config/routes.rb
Rails.application.routes.draw do
 
  root :to  => 'session#index'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' =>'session#destroy' 

  get '/change_password' => 'users#change_password'
  patch '/change_password' => 'users#update_password'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trades, :types, :users, :journals
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :check_if_logged_in
  layout "panel"
  #Getting all type of transaction
	def index
		@types = Type.all
	end

  #Fiding type of transaction to update
	def edit
		@type = Type.find_by(id: params[:id])
	end


  #Updating one type of transaction
	def update 
		@type = Type.find_by(id: params[:id])
		if  @type.update(name: params[:type][:name])
			flash[:notice] =  'Type of transaction was successfully updated.'
		else
			flash[:notice] =  'Something when wrong'
		end
	end

  #Generating new object of type of transaction
	def new
		@type = Type.new 
	end

  #Creating new type of transaction
	def create
		@type = Type.new(name: params[:type][:name])
		if @type.save
		flash[:notice] =  'Type of transaction was successfully updated.'
		else
		flash[:notice] =  'Something when wrong'
		end
	end

  
  #Deleting method
	def destroy
		@result = Type.find(params[:id])
		if @result.destroy
			@types = Type.all
			flash[:notice] =  "Type  #{@result.name}  was successfully deleted."
		else
			flash[:notice] =  'Something when wrong'
		end
	end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_with model: @type, local: false do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>
            <%= f.submit class:"btn btn-outline-info" %>
<% end %>

app/views/types/_messages.js.erb
  message("alert alert-<%= class_name %>", "<%= message %>", "messages" )

app/views/types/_modal.html.erb
<!-- Modal -->
<div class="modal fade " id="typeModal" tabindex="-1" aria-labelledby="typeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="typeModalLabel">Edit Type of transaction</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/types/_type.html.erb
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to type.name, edit_type_path(type.id), remote: true, :'id-attr' => type.id , :'data-bs-toggle' => 'modal', :'data-bs-target' => '#typeModal', class:'text-decoration-none'   %>
        <%= link_to 'Delete', type_path(type.id), remote: true , :'id-delete' => type.id, :method => 'delete', class:"btn btn-outline-danger" %>   
    </li>
 

app/views/types/create.js.erb
closeModal()
<% if !@type.errors.any?  %>
    el = document.querySelector("#render-types");
    el.insertAdjacentHTML("beforeend", "<%= j render(@type) %>")
    <%= render partial: "messages", locals: {class_name: "success", message: flash[:notice]} %>
<% else %>
    <%= render partial: "messages", locals: {class_name: "danger", message: flash[:notice]}  %>
<% end %>

app/views/types/destroy.js.erb
<% if !@result.errors.any? || !@types.errors.any? %>
    el = document.querySelector('#render-types')
    el.innerHTML = "<%= j render @types %>"
    <%= render partial: "messages", locals: {class_name: "success", message: flash[:notice]} %>
<% else %>
    <%= render partial: "messages", locals: {class_name: "danger", message: flash[:notice]}  %>
<% end %>

app/views/types/edit.js.erb
modalBody = document.querySelector('.modal-body')
modalBody.innerHTML = "<%= j render partial: 'form'%>"

app/views/types/index.html.erb
   <div class="container-fluid">
   <div class="row justify-content-md-center ">
      <div class="card col-xs-12 col-sm-12 col-md-8   reset-padding mt-3 " >
         <div class="card-header">Viewving of Types </div>
         <div class="card-body">
               <div class="d-flex justify-content-between"> 
                  <h4 class="card-title">Types of transactions </h4>
                  <%= link_to "Add New Type", new_type_path, remote: true, class: "btn btn-outline-dark mb-3", :'data-bs-toggle' => 'modal', :'data-bs-target' => '#typeModal'   %>
               </div>
               <div class="d-flex justify-content-between"> 
               </div>
            <div class="container messages"></div>
            <div class="row justify-content-md-center">
               <div class="col-xs-12 col-sm-12  col-md-12">
                  <ul class="list-group" id="render-types" >
                   <%= render  @types %>
                  </ul>
               </div>
            </div>
         </div>
      </div>
   </div>
<%= render partial:'modal' %>

app/views/types/new.js.erb
modalBody = document.querySelector('.modal-body')
modalBody.innerHTML = "<%= j render partial: 'form'%>"

app/views/types/update.js.erb
closeModal()
<% if !@type.errors.any? %>
link = document.querySelector("[id-attr='<%= @type.id %>']")
link.innerHTML = "<%= @type.name %>"
<%= render partial: "messages", locals: {class_name: "info", message: flash[:notice]} %>
<% else %>
<%= render partial: "messages", locals: {class_name: "danger", message: flash[:notice]}  %>
<% end %>