config/routes.rb
Rails.application.routes.draw do
 
  root :to  => 'session#index'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' =>'session#destroy' 

  get '/change_password' => 'users#change_password'
  patch '/change_password' => 'users#update_password'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trades, :types, :users, :journals
end

app/models/trade.rb
class Trade < ApplicationRecord
    belongs_to :user
    belongs_to :type 
    belongs_to :perpetual
    has_many :journals, :dependent => :delete_all
    validates :platform, :symbol, :leverage, :entry_date, :entry_price, :entry_amount, :exit_price, :exit_date,  presence: true 
    validates :entry_amount, :entry_price, :exit_price, numericality: { :greater_than  => 0 }


    def self.push_data(trade)
        if trade.perpetual.perpetual_type == 'long'
            trade.profit =  self.calc_long(trade.entry_price, trade.exit_price, trade.entry_amount, trade.leverage)
        else
            trade.profit =  self.calc_short(trade.entry_price, trade.exit_price, trade.entry_amount, trade.leverage)
        end 
        return trade
    end

    def self.calc_long(entry_price, exit_price, amount, leverage)
        leverage = leverage == 0 ? 1 : leverage
        #Formula ((1 / Futures Entry Price) - (1 / Futures Exit Price)) * Position Size
        position = (amount / entry_price)
        pnl = position * (exit_price - entry_price )
        result = pnl * leverage
        result
    end
    
    
    def self.calc_short(entry_price, exit_price, amount, leverage)
        leverage = leverage == 0 ? 1 : leverage
        position = (amount / entry_price)
        pnl = position * ( entry_price - exit_price )
        result = pnl * leverage
        result
    end
 

end

app/controllers/trades_controller.rb
class TradesController < ApplicationController

  before_action :check_if_logged_in
  layout "panel"
  def index
    @trades = Trade.where(user_id: @current_user.id)
  end

  def show
    @trades = Trade.find(params[:id])
    redirect_to login_path unless @trades.user_id == @current_user.id 
  end

  def edit
    @trade = Trade.find(params[:id])
  end

  def new
    @trade = Trade.new
  end

  def create
    @trade = Trade.new trade_params
    @trade  = Trade.push_data(@trade)
    @trade.save
    if  @trade.persisted?
      flash[:notice] = "Transaction has been created!"
      redirect_to trades_path    
    else
      flash[:error] = "Something went wrong try again"
      render :new                                                                                                                                                
    end
  end

  def destroy
    trade = Trade.find(params[:id])
    if trade.destroy
      redirect_to trades_path
      flash[:notice] = "Item has been deleted!"
    else
      redirect_to trade_path(params[:id])
      flash[:error] = "There's been an error deleting the item, contact admin."
    end
  end

  def update
    trade = Trade.find  params[:id]
    @trade  = Trade.push_data(trade)
    if @trade.update trade_params
      flash[:notice] = "Transaction has been updated!"
      redirect_to trade_path(params[:id])
    else
      flash[:error] = "Something went wrong try again"
      render :edit
    end
  end

  
  private def trade_params
    user = { user_id: @current_user.id }
    params.require(:trade).permit(:platform, :symbol, :type_id, :entry_date, :entry_price, :entry_amount, :exit_price, :leverage, :exit_date,:perpetual_id).reverse_merge(user)
  end

  
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/trades/_errors.html.erb
<% if flash[:notice] %>
    <div class="alert alert-dismissible alert-success">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Success!</strong> <%= flash[:notice] %>
    </div>
<% end %>   
<% if flash[:error] %>
    <div class="alert alert-dismissible alert-danger">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Failed!</strong> <%= flash[:error] %>
    </div>
<% end %>   

app/views/trades/_form.html.erb
<% if @trade.errors.any? %>
<div class="alert alert-dismissible alert-danger">
  <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  <ul>
    <% @trade.errors.full_messages.each do |el| %>
        <li>
            <%=el %>
        </li>
    <% end %>
    </ul>
</div>
    
<% end %>
<%= form_with model: @trade, local: true do |f| %>
    <div class=" col-md-12">
        <%= f.label :platform, class: 'form-label'  %>
        <%= f.text_field :platform, class: 'form-control', required: "true" %>
    </div>
    <div class="col-md-12">
        <%= f.label :symbol, class: 'form-label'  %>
        <%= f.text_field :symbol, class: 'form-control',  required: "true" %>
    </div>
     <div class="col-md-12">
        <%= f.label :leverage, class: 'form-label'  %>
        <%= f.text_field :leverage, class: 'form-control',  required: "true" %>
    </div>
     <div class="form-group col-md-12">
       <%= f.label :type_id, class: 'form-label'  %>
       <%=  f.collection_select :type_id, Type.all, :id, :name,{ include_blank: "Select option..." }, { class: "form-select",required: "true" }%>
    </div>
    <div class="form-group col-md-12">
       <%= f.label :perpetual_id, class: 'form-label'  %>
       <%=  f.collection_select :perpetual_id, Perpetual.all, :id, :perpetual_type,{ include_blank: "Select option..." }, { class: "form-select",  required: "true" } %>
    </div>
    <div class="col-md-12">
        <%= f.label :entry_date, class: 'form-label'  %>
        <%= f.text_field :entry_date, class: 'form-control datepicker_input',  required: "true" %>
    </div>
     <div class="col-md-12">
        <%= f.label :entry_price, class: 'form-label'  %>
        <%= f.text_field :entry_price, class: 'form-control',  required: "true" %>
    </div>
    <div class="col-md-12">
        <%= f.label :entry_amount, class: 'form-label'  %>
        <%= f.text_field :entry_amount, class: 'form-control',  required: "true" %>
    </div>
    <div class="col-md-12">
        <%= f.label :exit_price, class: 'form-label'  %>
        <%= f.text_field :exit_price, class: 'form-control',  required: "true" %>
    </div>
   
     <div class="col-md-12">
        <%= f.label :exit_date, class: 'form-label'  %>
        <%= f.text_field :exit_date, class: 'form-control datepicker_input',  required: "true" %>
    </div>
    <div class="col-md-12 ">
        <%= f.submit  class: 'btn btn-primary mt-3 col-md-4' %>
    </div>
<% end %>

app/views/trades/edit.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card border-light col-md-12 mt-5" >
                <div class="card-header bg-dark text-light">Editing Trade</div>
                <div class="card-body">
                      <%= render partial: 'form' %>
                </div>
            </div>
        </div>
    </div>
</div

app/views/trades/index.html.erb
<div class="d-flex justify-content-center align-items-center p-3" >
        <div class="col-md-3 p-2">
                        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
                            <div>
                                <h3 class="fs-4">Transactions</h3>
                            </div>
                        <i class="fas fa-chart-line fs-5 primary-text border rounded-full secondary-bg p-3"></i>
             </div>
         </div>
          <div class="col-md-3">
                        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
                            <div>
                               <h3 class="fs-4"><%=  link_to 'Add new', new_trade_path, class: "text-decoration-none"%></h3>
                            </div>
                            <i 
                                class="fas fa-plus fs-5 primary-text border rounded-full secondary-bg p-3"></i>
                        </div>
    </div>
</div>
<div class="container mt-3">
 <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 reset-padding">
         <%= render partial: 'errors' %>
  </div>
    <div class="table-responsive">
        <table class="table bg-white rounded shadow-sm  table-hover">
            <thead class="table-dark"> 
                 <th>Platform</th>
                 <th>Symbol</th>
                 <th>Type</th>
                 <th>Perpetual</th>
                 <th>Leverage</th>
                 <th>Entry Date </th>
                 <th>Exit Date</th>
                 <th>Position</th>
                 <th>Entry Price</th>
                 <th>Exit Price </th>
                 <th>PNL</th>
                 <th></th>
                 
             </thead>
              <tbody>
              <% if @trades.any? %>
                    <% @trades.each do |el| %>
                        <a href="#">
                            <tr>
                                <td><%= el.platform %> </td>
                                <td><%= el.symbol %> </td>
                                <td><%= el.type.name %> </td>
                                <td><%= el.perpetual.perpetual_type %> </td>
                                <td><%= el.leverage %> </td>
                                <td><%= el.entry_date.strftime("%d/%m/%Y") %> </td>
                                <td><%= el.exit_date.strftime("%d/%m/%Y") %>
                                <td><%= el.entry_amount %> </td>
                                <td><%= el.entry_price %> </td>
                                <td><%= el.exit_price %> </td>
                                </td>
                                <td class='<%= el.profit > 0 ? 'table-success ' : 'table-danger ' %> '>    
                                <%= number_to_currency(el.profit)%>
                                </td>
                                <td>
                                <%= link_to "View", trade_path(el.id),  class: "btn btn-outline-primary" %>
                                <%= link_to "Edit", edit_trade_path(el.id),  class: "btn btn-outline-dark" %>
                            </tr>
                        </a> 
                    <% end %>
                <% else %>
                    <tr>
                        <td colspan="12" class="text-center"> <h3>No trades yet.</h3>  </td>
                    </tr>
                <% end %>
             </tbody>
        </table>
    <div>
</div>

app/views/trades/new.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1>Add new trade </h1>
            <%= render partial: 'form' %>
        </div>
    </div>
</div>

app/views/trades/show.html.erb
<div class="container">
   <div class="row justify-content-md-center ">
      <div class="col sm-12 col-md-8 reset-padding">
         <%= render partial: 'errors' %>
      </div>
      <div class="card  col-sm-10 col-md-8   reset-padding mt-3 " >
          
         <div class="card-header">Viewing Transaction and Notes</div>
         <div class="card-body">
               <div class="d-flex justify-content-between"> 
                  <h4 class="card-title">Transaction </h4>
                  <div>
                     <%= link_to "Edit", edit_trade_path(@trades.id),  class: "btn btn-outline-dark mb-2" %>
                     <%= link_to "Delete", '#', class: "deleteItem btn btn-outline-danger mb-2", link_url: "/trades/#{@trades.id}", title: 'transaction' %>
                  </div>
               </div>
            <div class="row justify-content-md-center">
               <div class="col-xs-12 col-sm-12  col-md-6">
                  <ul class="list-group">
                     <li class="list-group-item d-flex justify-content-between align-items-center">
                        <h6>Platform:</h6>
                        <%= @trades.platform %>
                     </li>
                     <li class="list-group-item d-flex justify-content-between align-items-center">
                        <h6>Symbol:</h6>
                        <%= @trades.symbol %>
                     </li>
                     <li class="list-group-item d-flex justify-content-between align-items-center">
                        <h6>Entry Date:</h6>
                        <%= @trades.entry_date.strftime("%d/%m/%Y") %>
                     </li>
                     <li class="list-group-item d-flex justify-content-between align-items-center">
                        <h6>Exit Date:</h6>
                        <%= @trades.exit_date.strftime("%d/%m/%Y") %>
                     </li>
                  </ul>
               </div>
               <div class="col-xs-12 col-sm-12  col-md-6">
                  <li class="list-group-item d-flex justify-content-between align-items-center">
                     <h6>Perpetual:</h6>
                     <%= @trades.perpetual.perpetual_type %>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center">
                     <h6>Position:</h6>
                     <%= @trades.entry_amount %>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center">
                     <h6>Entry Price:</h6>
                     <%= @trades.entry_price %>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center">
                     <h6>Exit  Price:</h6>
                     <%= @trades.exit_price %>
                  </li>
               </div>
               <div class="col-xs-12 col-sm-12  col-md-12 mt-3 ">
                  <% if @trades.profit >= 0  %>
                           <div class="alert alert-dismissible alert-success p-4">
                              <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                              <strong>Well done!</strong> Total profits from this transaction: <%= number_to_currency(@trades.profit) %>
                           </div>
                  <% else %>
                         <div class="alert alert-dismissible alert-danger p-4">
                              <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                              <strong>Oh snap!</strong> Total losses from this transaction: <%= number_to_currency(@trades.profit)  %> 
                           
                           </div>
                  <% end %>
                  </div>
            </div>
            <div class="row justify-content-md-center mt-5">
               <div class="col-md-12">
                  <div class="d-flex justify-content-between"> 
                  <h4 class="card-title">Transactions Journal </h4>
                  <div>
                     <%= link_to "New Note", new_journal_path(:trade => @trades.id),  class: "btn btn-outline-dark mb-2" %>
                  </div>
               </div>
                  
                  <%@trades.journals.each do |el| %>
                  <div class="accordion mb-2" id="accordion<%= el.id %>">
                     <div class="accordion-item">
                        <h2 class="accordion-header" id="heading<%= el.id %>">
                           <button class="accordion-button collapsed reset-shadow" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= el.id %>" aria-expanded="false" aria-controls="collapse<%= el.id %>">
                           <%= el.journal_date.strftime("%d/%m/%Y") %>
                           </button>
                        </h2>
                        <div id="collapse<%= el.id %>" class="accordion-collapse collapse" aria-labelledby="heading<%= el.id %>" data-bs-parent="#accordion<%= el.id %>" >
                           <div class="accordion-body view-note-unique">
                              <input type="hidden" class="unique_note" value="<%= el.notes %>">
                              <div class="quill-show" >
                              </div>   
                              <div class="d-flex justify-content-end "> 
                                 <%= link_to "Edit", journal_path(el.id, :trade =>@trades.id ) , class: "btn btn-outline-primary mx-1" %>
                                 <%= link_to "Delete", '#', class: "deleteItem btn btn-outline-danger", link_url: "/journals/#{el.id}", title: "note from #{el.journal_date.strftime("%d/%m/%Y")}"  %>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               <% end %>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<div class="modal fade " id="confirmModal" tabindex="-1" aria-labelledby="confirmModalLabel" aria-hidden="true">
   <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
         <div class="modal-header" >
            <h4 class="modal-title" id="confirmModalLabel">Confirmation</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
         </div>
         <div class="modal-body">
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <%= link_to "Delete", '#', method: 'delete', class: 'btn btn-danger', id: 'deleteBtnModal' %>
         </div>
      </div>
   </div>
</div>