config/routes.rb
Rails.application.routes.draw do
 
  root :to  => 'session#index'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' =>'session#destroy' 

  get '/change_password' => 'users#change_password'
  patch '/change_password' => 'users#update_password'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trades, :types, :users, :journals
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TradingJournal</title>
    <%= favicon_link_tag 'favicon.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.2.0/dist/css/datepicker.min.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head> 
  <body>
    
<%= yield %>
 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.2.0/dist/js/datepicker-full.min.js"></script>
    <%= javascript_include_tag 'application' %>
  </body>
  </html>

app/views/layouts/panel.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>TradingJournal</title>
      <%= favicon_link_tag 'favicon.png' %>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.2.0/dist/css/datepicker.min.css">
      <link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
      <link href="//cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
      <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
      <%= stylesheet_link_tag    'application', media: 'all' %>
   </head>
   <body class="body-panel">
      <% if @current_user %>
      <div class="d-flex" id="wrapper">
         <!-- Sidebar -->
         <div class="bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading text-center py-4 primary-text fs-4 fw-bold text-uppercase border-bottom">
               <a class="navbar-brand" href="/"><%= image_tag "logo_transparent.png"  %></a>
            </div>
            <div class="list-group list-group-flush my-3">
                <%= link_to root_path, class:'list-group-item list-group-item-action bg-transparent  fw-bold active' do %>
                    <i class="fas fa-tachometer-alt me-2"></i>Home
                 <% end %>

                <%= link_to trades_path, class:'list-group-item list-group-item-action bg-transparent  fw-bold' do %>
                    <i class="fas fa-chart-line me-2"></i>Trades</a>
                 <% end %>
                
                <%= link_to types_path, class:'list-group-item list-group-item-action bg-transparent  fw-bold' do %>
                    <i class="fas fa-project-diagram me-2"></i>Types
                 <% end %>


                 <%= link_to user_path(@current_user.id), class:'list-group-item list-group-item-action bg-transparent  fw-bold' do %>
                    <i class="fas fa-user me-2"></i>Profile
                 <% end %>

                 <%= link_to login_path, class:'list-group-item list-group-item-action bg-transparent text-danger fw-bold', method:'delete' do %>
                    <i class="fas fa-power-off me-2"></i>Logout
                 <% end %>
            </div>
         </div>
         <!-- /#sidebar-wrapper -->
         <!-- Page Content -->
         <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent py-4 px-4">
               <div class="d-flex align-items-center">
                  <i class="fas fa-align-left primary-text fs-4 me-3" id="menu-toggle"></i>
                  <h2 class="fs-2 m-0">Dashboard</h2>
               </div>
               <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                  aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                     <li class="nav-item dropdown">
                        <a class="nav-link  second-text fw-bold" href="#" id="navbarDropdown"
                           role="button"  aria-expanded="false">
                        <i class="fas fa-user me-2"></i><%= @current_user.name %>
                        </a>
                     </li>
                  </ul>
               </div>
            </nav>
            <% end %>
            <div class="row my-5">
               <div class="col">
                  <%= yield %>
               </div>
            </div>
         </div>
      </div>
      </div>
      <!-- /#page-content-wrapper -->
      </div>
      <script>
         let el = document.getElementById("wrapper");
         let toggleButton = document.getElementById("menu-toggle");
         
         toggleButton.onclick = function () {
             el.classList.toggle("toggled");
         };
      </script>
      <script src="//cdn.quilljs.com/1.3.6/quill.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.2.0/dist/js/datepicker-full.min.js"></script>
      <%= javascript_include_tag 'application' %>
   </body>
</html>